### DISCUSSION TITLE
"Edit page" is very slow.

### DISCUSSION THREAD

**Discussion by towerstreet** [redimp/otterwiki#173] [Q&A]
- Read the page is OK, but "Edit page" is very slow. 
- And sometimes it show's the 502 error page.
What should I do?

**Comment by redimp** [comment]
Hey @towerstreet,

to be sure that this is not a client problem, does the [Demo](https://demo.otterwiki.com) work for you?

For the non-client problems I need some information. How and where did you deploy An Otter Wiki?

**Reply by towerstreet** [reply]
🎈Thanks.

👌The Demo works fine. 'Edit page' is fast.

🖥️I deploy it on my Server:
- CPU Athlon 200GE
- Ubuntu Server 24.04.1
- Docker version 27.2.0, build 3ab4256
- The container's data is storing in a HDD.

⚙️docker-compose.yml
```yaml
services:
  otterwiki:
    image: redimp/otterwiki:latest
    container_name: wiki
    restart: unless-stopped
    ports:
    - 8888:80
    volumes:
    - /home/towerstreet/Storage/Docker/Otterwiki/Data:/app-data
    environment:
      SITE_NAME: Wiki
      TZ: Asia/Shanghai
```

Does anything go wrong?
