### ISSUE TITLE
PostgreSQL database initialization seems to fail

### ISSUE THREAD

**Issue by mattock** [redimp/otterwiki#137]
I attempted to switch from SQLite to PostgreSQL (16.4) and ran into issues during database initialization:

```
2024-09-10 08:11:11.354 UTC [64] ERROR:  syntax error at or near "user" at character 13
2024-09-10 08:11:11.354 UTC [64] STATEMENT:  ALTER TABLE user ADD COLUMN email_confirmed BOOLEAN;
```

This repeat over and over again. I attempted to run the same command manually from the postgresql:16.4 container and the error was exactly the same. Database initialization did succeed *partially*, however:

```
otterwiki=# \dt
            List of relations
 Schema |    Name     | Type  |   Owner   
--------+-------------+-------+-----------
 public | drafts      | table | otterwiki
 public | preferences | table | otterwiki
(2 rows)
```

So, the database connectivity as configured in settings.cfg did work as expected.

Is postgresql supported / tested?

**Comment by redimp** [comment]
Hey @mattock, 

The [_db_migrate()](https://github.com/redimp/otterwiki/blob/44a308bd6e5593cb268c26b284d9edc3523b9351/otterwiki/auth.py#L66) function is poorly implemented, I'm sorry for that. Will look into this and test it against at least postgres.

**Comment by mattock** [comment]
@redimp ok, thanks!

**Comment by redimp** [comment]
I've removed the obsolete and poorly implemented `_db_migrate` function, fixed some datatypes and lengths (that fortunately break nothing in SQlite.)

For testing I used this `docker-compose.yaml`:

```yaml
---
services:
  web:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:example@db/postgres
    command:
      - /bin/bash
      - -c
      - |
        pip install psycopg2-binary
        /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - 8080:80

  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8082:8080
```
