### ISSUE TITLE
Is the helm chart in the same OCI path as the docker image with the same name?

### ISSUE THREAD

**Issue by skillpoint-dev** [redimp/otterwiki#171]
My flux keeps telling me that I should upgrade my otterwiki helm chart to version 2.8.0 but there is none.

Repository:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otterwiki
  namespace: otterwiki
spec:
  interval: 5m
  type: oci
  url: oci://registry-1.docker.io/redimp
```

HelmRelease:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otterwiki
  namespace: otterwiki
spec:
  releaseName: otterwiki
  chart:
    spec:
      chart: otterwiki
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: otterwiki
...
```

Could it be that the container and the helm chart are store with the same name in the same path or am I overlooking something here?

**Comment by redimp** [comment]
Hey @skillpoint-dev, 

> Could it be that the container and the helm chart are store with the same name in the same path or am I overlooking something here?

Yes, thats the problem you ran into. That's my bad .. I had not thought that through when I decided to use the docker registry for the helmchart, too.

I have https://charts.otterwiki.com ready to be used, but I did not update the documentation yet. Please give it a shot:

```
helm repo add otterwiki https://charts.otterwiki.com
helm repo update
```

for fluxcd update the manifest to

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otterwiki
  namespace: otterwiki
spec:
  interval: 15m0s
  url: https://charts.otterwiki.com
```

I appreciate feedback!
